### ISSUE TITLE
Any way to suppress console output?

### ISSUE THREAD

**Issue by mahemoff** [emrekutlu/paperclip-compression#13]
I see a lot of noise in test output, I think it's mainly optipng. What are thoughts on defining [OPTIPNG_DEFAULT_OPTS in png.rb](https://github.com/emrekutlu/paperclip-compression/blob/95bc76ce8b3b5cefdb90cde958a4fdbdf9b33055/lib/paperclip-compression/png.rb#L4) to include a -q for quiet output?

**Comment by emrekutlu** [comment]
Sounds good.

**Comment by emrekutlu** [comment]
<code>quiet</code> option added on v0.3.11.

**Comment by mahemoff** [comment]
Thanks
