### ISSUE TITLE
Could compression of `png` files also re-open the destination file?

### ISSUE THREAD

**Issue by zspencer** [emrekutlu/paperclip-compression#16]
We've discovered that when paperclip-compression compresses png files and swaps the file pointer from the original to the newly compressed version of the file; the newly compressed version of the file has a size of `0` bytes.

However, if you re-open the file (Such as in the jpg compressor), the `size` instance method correctly reflects the size of the file.

```
[26, 35] in /Users/zee/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/paperclip-compression-0.3.14/lib/paperclip-compression/png.rb
   26:
   27:     def process_file
   28:       Paperclip.run(command_path('optipng'), "#{@cli_opts} -clobber :src_path -out :dst_path", src_path: @src_path, dst_path: @dst_path)
   29:       require 'byebug'
   30:       byebug
=> 31:       @dst
   32:     end
   33:
   34:   end
   35: end
(byebug) @dst.size
0
(byebug) @dst.open
#<File:/var/folders/sx/s1fjq54x2rl0808_hwt52spr0000gn/T/fd7bc86e8c3159466e78d185b79251bb20160330-27063-qqnz5q.png>
(byebug) @dst.size
21417
```

This can cause problems with downstream processors (Such as paperclip-meta, which sets the meta attribute for the file size to 0)

I don't know what side effects could occur downstream (For instance, do some processors treat files with a size of 0 differently? Do any depend on this behavior for other reasons?)

Thoughts?

**Comment by emrekutlu** [comment]
No specific reason for that. It seems like a bug.
If you have the fixed version, a PR is  welcomed.

**Comment by zspencer** [comment]
Oops! Forgot to cc @etlund who I was pairing with on this :). I think he has the code fix on a branch on his machine!

**Comment by zspencer** [comment]
Meh, figured I'd re-implement over coffee.
