### ISSUE TITLE
exist some way to compress original image?

### ISSUE THREAD

**Issue by jvalenciag** [emrekutlu/paperclip-compression#18]

**Comment by emrekutlu** [comment]
Sorry, I didn't understand what you meant.
Can you explain in more detail?

**Comment by vibhoo** [comment]
How to compress the original uploaded image size.

**Comment by emrekutlu** [comment]
No, as far as I know you can't. Because paperclip do not let the processors change the original image.

> NOTE: Because processors operate by turning the original attachment into the styles, no processors will be run if there are no styles defined.

This is the note on this page https://github.com/thoughtbot/paperclip#post-processing.
