### ISSUE TITLE
Use OS binaries instead of vendorized binaries

### ISSUE THREAD

**Issue by marclennox** [emrekutlu/paperclip-compression#20]
Paperclip compression doesn't work on Alpine Linux because of the vendorized binaries.  Is there a setting to force this gem to use native OS installed binaries instead?

**Comment by emrekutlu** [comment]
No, there isn't a way to do that. But sounds like a good feature to add.

**Comment by emrekutlu** [comment]
@pdfrod I made some changes on `develop` branch. Now options accepts a hash. Can you test it?

In your Gemfile:
```
gem 'paperclip-compression', github: 'emrekutlu/paperclip-compression', branch: 'develop'
```

In you model:
```ruby
class User < ActiveRecord::Base
  has_attached_file :avatar,
    styles: {
      thumb: {
        geometry: '100x100>',
        processor_options: {
          compression: {
            jpeg: {
              command: '/path/to/jpegtran',
              options: '-copy none -optimize'
            }
          }
        }
      }
    },
    processors: [:thumbnail, :compression]
end
```

**Comment by pdfrod** [comment]
@emrekutlu I've just tested and it works. Thanks!

**Comment by emrekutlu** [comment]
Great. `1.0.0` released. No backward incompatible changes. You can upgrade right away.
