### ISSUE TITLE
Fails on macOS Catalina

### ISSUE THREAD

**Issue by eivrei** [emrekutlu/paperclip-compression#25]
Image compression fails on macOS 10.15 - Catalina.
Error message: 
`Paperclip::Error: JPEGTRAN : There was an error processing f9aaf99b6da6fe2f2c247a8bc707caab20191015-14554-xej91e`

Code that triggers the compressor: 
```ruby
has_attached_file :image_file,
                    styles: { medium: 'x180>', large: 'x400>' },
                    convert_options: { medium: '-quality 80', large: '-quality 80' },
                    processors: %i[thumbnail compression],
                    url: '/upload/:class/:attachment/:id_partition/:style/:filename',
                    path: ':rails_root/public/upload/:class/:attachment/:id_partition/:style/:filename',
                    default_url: '/home/.../kitteh.jpeg'
```

**Comment by robikovacs** [comment]
Experienced the same issue with:

**Comment by emrekutlu** [comment]
Hi all, can you test `catalina` branch please?

**Comment by nashby** [comment]
@emrekutlu it works! (just need to rebuild ruby if it was installed on previous OSX version)

**Comment by emrekutlu** [comment]
Thank you @nashby. `1.1.0` has been released.
