### ISSUE TITLE
Support for kt-paperclip

### ISSUE THREAD

**Issue by traviskroberts** [emrekutlu/paperclip-compression#32]
Since [paperclip has been deprecated](https://thoughtbot.com/blog/closing-the-trombone), a new maintainer has stepped forward with their [own version of paperclip](https://github.com/kreeti/kt-paperclip). Would it be possible to change the gemspec to reference the new gem? If not in master, maybe have a `kt-paperclip` branch?

**Comment by emrekutlu** [comment]
Hi Travis, maybe it is better to do the same for this gem as well, just forking it and creating a new gem.

**Comment by portwood** [comment]
Is there any update on a kt-paperclip version of paperclip-compression? I'm stuck on Ruby 2.7.x until this is resolved.

**Comment by emrekutlu** [comment]
I didn't test this but there is a fork for `kt-paperclip`.
https://github.com/adamtao/kt-paperclip-compression

**Comment by portwood** [comment]
Thanks!

**Comment by traviskroberts** [comment]
I'm gonna go ahead and close this issue since a fork that supports kt-paperclip exists now.
