### ISSUE TITLE
Version 1.1.1 fails on MacOS

### ISSUE THREAD

**Issue by portwood** [emrekutlu/paperclip-compression#33]
When run on MacOS Catalina 10.15.7, I receive an "undefined method '[]' for nil:NilClass"
Investigating further, I found the cause on Lines 77-80 of base.rb
```
   def catalina?
      major = OS.host_os.match(/darwin(\d+)\./)[1].to_i
      major >= 19
    end

```
OS.host_os on my Mac returns 'darwin19'
It appears that the match is failing, returning nil, causing the [1] to raise an exception.

Same is true with kt-paperclip-compression

**Comment by sorenwiz** [comment]
Try this initializer
```
Rails.application.config.to_prepare do

  PaperclipCompression::Base.class_eval do
    def catalina?
      major = OS.host_os.match(/darwin(\d+)/)[1].to_i
      major >= 19
    end

  end
end

**Comment by portwood** [comment]
That appears to fix the issue

**Comment by emrekutlu** [comment]
Hi @portwood, what is your ruby version?

**Comment by sorenwiz** [comment]
I have the issue on 2.7.3

**Comment by portwood** [comment]
2.7.3

**Comment by sorenwiz** [comment]
Let me see if I can make a PR - First time i try that :-)

**Comment by sorenwiz** [comment]
Ok I made a PR now, let me know if you have any comments. Different versions of rails or ruby gives a slightly different OS string

**Comment by emrekutlu** [comment]
Thank you @sorenwiz for the PR. It has been merged, hopefully I will release the new version tomorrow.

**Comment by emrekutlu** [comment]
`v2.0.0` has been released. No breaking change for you, I've bumped the major version because it drops Ruby 2.1 & 2.2 support.
