### ISSUE TITLE
Rails 4.1.rc2 app won't boot

### ISSUE THREAD

**Issue by erikdahlstrand** [emrekutlu/paperclip-compression#7]
Hi,

With 'paperclip-compression' in my Gemfile the rails app won't boot.

I get the following error when starting the web server

    $ rails s
    .rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/parser-2.1.7/lib/parser/ruby21.rb:13:in `<top (required)>': undefined method `check_for_encoding_support' for Parser:Module (NoMethodError)

**Comment by uiltondutra** [comment]
The ruby-imagespec dependency was removed. I think this discussion can be closed.

**Comment by emrekutlu** [comment]
Yes, I am closing it. Actually I should close with the previous version, sorry about that.
